[workspace]
authors = ["David W.H. Swenson <david.swenson@omsf.io>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "ami-builder"
platforms = ["osx-64"]
version = "0.1.0"

[tasks]
build-ami = "packer init build-ami.pkr.hcl && packer build -var 'ami_name=omsf' -var 'default_environment=openfe' -var 'environments=[\"openfe\",\"openpathsampling\"]' build-ami.pkr.hcl"
build-docker = "packer init build-docker.pkr.hcl && packer build -var 'ami_name=omsf' -var 'default_environment=openfe' -var 'environments=[\"openfe\",\"openpathsampling\"]' -var \"build_timestamp=$(date +%s)\" build-docker.pkr.hcl"

[dependencies]
python = "*"
boto3 = "*"
click = "*"
pyyaml = "*"

pytest = "*"
moto = "*"
pytest-cov = "*"
