[workspace]
authors = ["David W.H. Swenson <david.swenson@omsf.io>"]
channels = ["conda-forge"]
description = "Pixi workspace for image runtime and test environments"
name = "omsf-image-environments"
platforms = ["linux-64"]
version = "0.1.0"

[tool.image-builder]
image_name = "omsf"
default_environment = "openfe"
environments = ["openfe"]#, "openpathsampling"]

[system-requirements]
cuda = "12"


# OpenFE
[feature.openfe.dependencies]
openfe = "*"

[feature.openfe-test]

[environments.openfe]
features = ["openfe"]
solve-group = "openfe"
no-default-feature = true

[environments.openfe-test]
features = ["openfe", "openfe-test"]
solve-group = "openfe"
no-default-feature = true

# OpenPathSampling
[feature.openpathsampling.dependencies]
openpathsampling = "*"
openpathsampling-cli = "*"

[feature.openpathsampling-test.dependencies]
pytest = "*"

[environments.openpathsampling]
features = ["openpathsampling"]
solve-group = "openpathsampling"
no-default-feature = true

[environments.openpathsampling-test]
features = ["openpathsampling", "openpathsampling-test"]
solve-group = "openpathsampling"
no-default-feature = true

# OMSF
[environments.omsf]
features = ["openfe", "openpathsampling"]
solve-group = "omsf"
no-default-feature = true

[environments.omsf-test]
features = [
  "openfe", "openfe-test",
  "openpathsampling", "openpathsampling-test"
]
solve-group = "omsf"
no-default-feature = true
